import type { LoadHook, Module, ResolveHook } from 'node:module'
import { dirname, resolve as pathResolve, relative } from 'node:path'
import process from 'node:process'
import { fileURLToPath, pathToFileURL } from 'node:url'
import fg from 'fast-glob'

const GLOB_PREFIX = 'glob:'
const VIRTUAL_GLOB_PREFIX = 'virtual-glob-module:'

interface GlobImportDetails {
  basePattern: string
  globOptions: URLSearchParams
}

function parseDetailsFromAttributes(
  specifier: string,
  attributes: Module.ImportAttributes,
): GlobImportDetails {
  const basePattern = specifier
  const globOptions = new URLSearchParams()

  for (const key in attributes) {
    if (key !== 'type' && Object.prototype.hasOwnProperty.call(attributes, key)) {
      globOptions.set(key, String(attributes[key]))
    }
  }
  return { basePattern, globOptions }
}

function parseDetailsFromPrefix(specifier: string): GlobImportDetails {
  let basePattern: string
  const globOptions = new URLSearchParams()
  const patternPartWithoutPrefix = specifier.substring(GLOB_PREFIX.length)

  const queryIndex = patternPartWithoutPrefix.indexOf('?')
  if (queryIndex !== -1) {
    const queryString = patternPartWithoutPrefix.substring(queryIndex + 1)
    const queryBasedOptions = new URLSearchParams(queryString)
    for (const [key, value] of queryBasedOptions) {
      globOptions.set(key, value)
    }
    basePattern = patternPartWithoutPrefix.substring(0, queryIndex)
  } else {
    basePattern = patternPartWithoutPrefix
  }
  return { basePattern, globOptions }
}

function tryParseGlobImport(
  specifier: string,
  importAttributes: Module.ImportAttributes,
): GlobImportDetails | null {
  if (importAttributes.type === 'glob') {
    return parseDetailsFromAttributes(specifier, importAttributes)
  }

  if (specifier.startsWith(GLOB_PREFIX)) {
    return parseDetailsFromPrefix(specifier)
  }

  return null
}

export const resolve: ResolveHook = async (specifier, context, nextResolve) => {
  const globDetails = tryParseGlobImport(specifier, context.importAttributes)

  if (globDetails) {
    const { basePattern, globOptions } = globDetails
    const importerBaseDir =
      context.parentURL != null ? dirname(fileURLToPath(context.parentURL)) : process.cwd()

    const absoluteGlobPattern = pathResolve(importerBaseDir, basePattern)

    const resolvedImportAttributes: Record<string, string> = {}
    for (const [key, value] of globOptions.entries()) {
      resolvedImportAttributes[key] = value
    }
    resolvedImportAttributes.importerDir = importerBaseDir

    return {
      shortCircuit: true,
      url: `${VIRTUAL_GLOB_PREFIX}${absoluteGlobPattern}`,
      importAttributes: resolvedImportAttributes,
    }
  }

  return nextResolve(specifier, context)
}

export const load: LoadHook = async (url, context, nextLoad) => {
  if (url.startsWith(VIRTUAL_GLOB_PREFIX)) {
    const absoluteGlobPattern = url.substring(VIRTUAL_GLOB_PREFIX.length)
    const passedAttributes = context.importAttributes

    const importerDir = passedAttributes.importerDir ?? process.cwd()
    const mode =
      typeof passedAttributes.eager === 'string' && passedAttributes.eager === 'true'
        ? 'eager'
        : 'lazy'

    const posixAbsoluteGlobPattern = absoluteGlobPattern.replace(/\\\\/g, '/')

    const fgOptions: Record<string, any> = { absolute: true, onlyFiles: true }
    for (const key in passedAttributes) {
      if (
        Object.prototype.hasOwnProperty.call(passedAttributes, key) &&
        key !== 'importerDir' &&
        key !== 'eager'
      ) {
        if (passedAttributes[key] === 'true') {
          fgOptions[key] = true
        } else if (passedAttributes[key] === 'false') {
          fgOptions[key] = false
        } else {
          fgOptions[key] = passedAttributes[key]
        }
      }
    }

    const files = await fg(posixAbsoluteGlobPattern, fgOptions)

    let importCounter = 0
    const importStatements: string[] = []
    const properties: string[] = []

    for (const absoluteFilePath of files) {
      const moduleFileUrl = pathToFileURL(absoluteFilePath).href
      let relativePathKey = relative(importerDir, absoluteFilePath).replace(/\\\\/g, '/')
      if (!relativePathKey.startsWith('.')) {
        relativePathKey = `./${relativePathKey}`
      }

      if (mode === 'eager') {
        const importName = `__globbed_eager_${importCounter++}`
        importStatements.push(`import * as ${importName} from '${moduleFileUrl}';`)
        properties.push(`'${relativePathKey}': ${importName}`)
      } else {
        properties.push(`'${relativePathKey}': () => import('${moduleFileUrl}')`)
      }
    }

    const source = `
      // Dynamically generated by globload
      ${importStatements.join('\n')}
      
      export default {
        ${properties.join(',\n')}
      };
    `

    return {
      shortCircuit: true,
      format: 'module',
      source,
    }
  }
  return nextLoad(url, context)
}
